.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-BLOG\-DELETE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-blog\-delete\fR \- Delete a blog in a multisite install\.
.
.SH "SYNOPSIS"
wp blog delete [\fIblog\-id\fR] [\-\-slug=\fIslug\fR] [\-\-yes] [\-\-keep\-tables]
.
.SH "OPTIONS"
.
.TP
\fB<blog\-id>\fR:
.
.IP
The id of the blog to delete\. If not provided, you must set the \-\-slug parameter\.
.
.TP
\fB\-\-slug\fR=\fIslug\fR:
.
.IP
Path of the blog to be deleted\. Subdomain on subdomain installs, directory on subdirectory installs\.
.
.TP
\fB\-\-yes\fR:
.
.IP
Answer yes to the confirmation message\.
.
.TP
\fB\-\-keep\-tables\fR:
.
.IP
Delete the blog from the list, but don\'t drop it\'s tables\.

