.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-CACHE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-cache\fR \- Manage the object cache\.
.
.SH "SYNOPSIS"
wp cache add \fIkey\fR \fIvalue\fR [\fIgroup\fR] [\fIexpiration\fR]
.
.P
wp cache decr \fIkey\fR [\fIoffset\fR] [\fIgroup\fR]
.
.P
wp cache delete \fIkey\fR \fIgroup\fR
.
.P
wp cache flush
.
.P
wp cache get \fIkey\fR [\fIgroup\fR]
.
.P
wp cache incr \fIkey\fR [\fIoffset\fR] [\fIgroup\fR]
.
.P
wp cache replace \fIkey\fR \fIvalue\fR [\fIgroup\fR] [\fIexpiration\fR]
.
.P
wp cache set \fIkey\fR \fIvalue\fR [\fIgroup\fR] [\fIexpiration\fR]
.
.P
wp cache type
.
.SH "SUBCOMMANDS"
.
.TP
\fBadd\fR:
.
.IP
Add a value to the object cache\.
.
.TP
\fBdecr\fR:
.
.IP
Decrement a value in the object cache\.
.
.TP
\fBdelete\fR:
.
.IP
Remove a value from the object cache\.
.
.TP
\fBflush\fR:
.
.IP
Flush the object cache\.
.
.TP
\fBget\fR:
.
.IP
Get a value from the object cache\.
.
.TP
\fBincr\fR:
.
.IP
Increment a value in the object cache\.
.
.TP
\fBreplace\fR:
.
.IP
Replace an existing value in the object cache\.
.
.TP
\fBset\fR:
.
.IP
Set a value to the object cache\.
.
.TP
\fBtype\fR:
.
.IP
Attempts to determine which object cache is being used\.
.
.SH "EXAMPLES"

.
.P
wp cache set my_key my_value my_group 300
.
.P
wp cache get my_key my_group
