.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-SPAM" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-spam\fR \- Spam a comment\.
.
.SH "SYNOPSIS"
wp comment spam \fIid\fR
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the comment to mark as spam\.
.
.SH "EXAMPLES"
.
.nf

wp comment spam 1337
.
.fi

