.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-COUNT" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-count\fR \- Count comments, on whole blog or on a given post\.
.
.SH "SYNOPSIS"
wp comment count [\fIpost\-id\fR]
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the post to count comments in
.
.SH "EXAMPLES"
.
.nf

wp comment count
wp comment count 42
.
.fi

