.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-UNTRASH" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-untrash\fR \- Untrash a comment\.
.
.SH "SYNOPSIS"
wp comment untrash \fIid\fR
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the comment to untrash\.
.
.SH "EXAMPLES"
.
.nf

wp comment untrash 1337
.
.fi

