.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-COUNT" "1" "September 2012" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-count\fR \- Get total comments for blog or single post
.
.SH "SYNOPSIS"
\fBwp comment count\fR [\fIID\fR]
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the post to count comments in
.
.SH "EXAMPLES"
.
.nf

wp comment count
wp comment count 42
.
.fi

