.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-DELETE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-delete\fR \- Delete a comment\.
.
.SH "SYNOPSIS"
wp comment delete \fIid\fR [\-\-force]
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the comment to delete\.
.
.TP
\fB\-\-force\fR:
.
.IP
Skip the trash bin\.
.
.SH "EXAMPLES"
.
.nf

wp comment delete 1337 \-\-force
.
.fi

