.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-UNSPAM" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-unspam\fR \- Unspam a comment\.
.
.SH "SYNOPSIS"
wp comment unspam \fIid\fR
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the comment to unmark as spam\.
.
.SH "EXAMPLES"
.
.nf

wp comment unspam 1337
.
.fi

