.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-LAST" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-last\fR \- Get last approved comment\.
.
.SH "SYNOPSIS"
wp comment last [\-\-id] [\-\-full]
.
.SH "OPTIONS"
.
.TP
\fB\-\-id\fR:
.
.IP
Output just the last comment id\.
.
.TP
\fB\-\-full\fR:
.
.IP
Output complete comment information\.
.
.SH "EXAMPLES"
.
.nf

wp comment last \-\-full
.
.fi

