.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-COMMENT\-UNAPPROVE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-comment\-unapprove\fR \- Unapprove a comment\.
.
.SH "SYNOPSIS"
wp comment unapprove \fIid\fR
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the comment to unapprove\.
.
.SH "EXAMPLES"
.
.nf

wp comment unapprove 1337
.
.fi

