.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-CORE\-DOWNLOAD" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-core\-download\fR \- Download core WordPress files\.
.
.SH "SYNOPSIS"
wp core download [\-\-locale=\fIlocale\fR] [\-\-version=\fIversion\fR] [\-\-path=\fIpath\fR] [\-\-force]
.
.SH "OPTIONS"
.
.TP
\fB\-\-locale\fR=\fIlocale\fR:
.
.IP
Select which language you want to download\. The \-\-version parameter is ignored in this case\.
.
.TP
\fB\-\-version\fR=\fIversion\fR:
.
.IP
Select which version you want to download\.
.
.TP
\fB\-\-force\fR:
.
.IP
Overwrites existing files, if present\.
.
.SH "EXAMPLES"
.
.nf

Download version 3\.3: wp core download \-\-version=3\.3
.
.fi

