.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-CORE\-INSTALL\-NETWORK" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-core\-install\-network\fR \- Transform a single\-site install into a multi\-site install\.
.
.SH "SYNOPSIS"
wp core install\-network \-\-title=\fInetwork\-title\fR [\-\-base=\fIurl\-path\fR]
.
.SH "OPTIONS"
.
.TP
\fB\-\-title\fR=\fIsite\-title\fR:
.
.IP
The title of the new network\.
.
.TP
\fB\-\-base\fR=\fIurl\-path\fR:
.
.IP
Base path after the domain name that each site url will start with\. Default: \'/\'

