.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-CORE\-INSTALL" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-core\-install\fR \- Create the WordPress tables in the database\.
.
.SH "SYNOPSIS"
wp core install \-\-url=\fIurl\fR \-\-title=\fIsite\-title\fR [\-\-admin_name=\fIusername\fR] \-\-admin_email=\fIemail\fR \-\-admin_password=\fIpassword\fR
.
.SH "OPTIONS"
.
.TP
\fB\-\-url\fR=\fIurl\fR:
.
.IP
The address of the new site\.
.
.TP
\fB\-\-title\fR=\fIsite\-title\fR:
.
.IP
The title of the new site\.
.
.TP
\fB\-\-admin_name\fR=\fIusername\fR:
.
.IP
The name of the admin user\. Default: \'admin\'
.
.TP
\fB\-\-admin_password\fR=\fIpassword\fR:
.
.IP
The password for the admin user\.
.
.TP
\fB\-\-admin_email\fR=\fIemail\fR:
.
.IP
The email address for the admin user\.

