.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-CORE\-VERSION" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-core\-version\fR \- Display the WordPress version\.
.
.SH "SYNOPSIS"
wp core version [\-\-extra]
.
.SH "OPTIONS"
.
.TP
\fB\-\-extra\fR:
.
.IP
Show extended version information\.

