.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-CORE\-CONFIG" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-core\-config\fR \- Set up a wp\-config\.php file\.
.
.SH "SYNOPSIS"
wp core config \-\-dbname=\fIname\fR \-\-dbuser=\fIuser\fR [\-\-dbpass=\fIpassword\fR] [\-\-dbhost=\fIhost\fR] [\-\-dbprefix=\fIprefix\fR] [\-\-extra\-php]
.
.SH "OPTIONS"
.
.TP
\fB\-\-dbname\fR=\fIdbname\fR:
.
.IP
Set the database name\.
.
.TP
\fB\-\-dbuser\fR=\fIdbuser\fR:
.
.IP
Set the database user\.
.
.TP
\fB\-\-dbpass\fR=\fIdbpass\fR:
.
.IP
Set the database user password\.
.
.TP
\fB\-\-dbhost\fR=\fIdbhost\fR:
.
.IP
Set the database host\. Default: \'localhost\'
.
.TP
\fB\-\-dbprefix\fR=\fIdbprefix\fR:
.
.IP
Set the database table prefix\. Default: \'wp_\'
.
.TP
\fB\-\-extra\-php\fR:
.
.IP
If set, the command reads additional PHP code from STDIN\.
.
.SH "EXAMPLES"
.
.nf

# Standard wp\-config\.php file
wp core config \-\-dbname=testing \-\-dbuser=wp \-\-dbpass=securepswd

# Enable WP_DEBUG and WP_DEBUG_LOG
wp core config \-\-dbname=testing \-\-dbuser=wp \-\-dbpass=securepswd \-\-extra\-php <<PHP
define( \'WP_DEBUG\', true );
define( \'WP_DEBUG_LOG\', true );
PHP
.
.fi

