.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-CORE\-IS\-INSTALLED" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-core\-is\-installed\fR \- Determine if the WordPress tables are installed\.
.
.SH "SYNOPSIS"
wp core is\-installed
.
.SH "EXAMPLES"
if ! $(wp core is\-installed); then
.
.IP "" 4
.
.nf

wp core install
.
.fi
.
.IP "" 0
.
.P
fi
