.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-DB\-IMPORT" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-db\-import\fR \- Import database from a file\.
.
.SH "SYNOPSIS"
wp db import [\fIfile\fR]
.
.SH "OPTIONS"
.
.TP
\fB<file>\fR:
.
.IP
The name of the import file\. If omitted, it will be \'{dbname}\.sql\'

