.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-DB\-RESET" "1" "August 2012" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-db\-reset\fR \- Remove all data from the database specified in wp\-config\.php
.
.SH "SYNOPSIS"
\fBwp db reset\fR [\-\-yes]
.
.SH "OPTIONS"
.
.TP
\fB\-\-yes\fR:
.
.IP
Answer yes to the confirmation message\.

