.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-DB\-RESET" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-db\-reset\fR \- Remove all tables from the database\.
.
.SH "SYNOPSIS"
wp db reset [\-\-yes]
.
.SH "OPTIONS"
.
.TP
\fB\-\-yes\fR:
.
.IP
Answer yes to the confirmation message\.

