.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-EXPORT" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-export\fR \- Export content to a WXR file\.
.
.SH "SYNOPSIS"
wp export [\-\-dir=\fIdir\fR] [\-\-start_date=\fIdate\fR] [\-\-end_date=\fIdate\fR] [\-\-post_type=\fIptype\fR] [\-\-post_status=\fIstatus\fR] [\-\-post__in=\fIpids\fR] [\-\-author=\fIlogin\fR] [\-\-category=\fIcat\fR] [\-\-skip_comments] [\-\-file_item_count=\fIcount\fR]
.
.SH "OPTIONS"
.
.TP
\fB\-\-dir\fR=\fIdirname\fR:
.
.IP
Full path to directory where WXR export files should be stored\. Defaults to current working directory\.
.
.TP
\fB\-\-skip_comments\fR:
.
.IP
Don\'t export comments\.
.
.TP
\fB\-\-file_item_count\fR=\fIcount\fR:
.
.IP
Break export into files with N posts\.
.
.SH "FILTERS"
.
.TP
\fB\-\-start_date\fR=\fIdate\fR:
.
.IP
Export only posts newer than this date, in format YYYY\-MM\-DD\.
.
.TP
\fB\-\-end_date\fR=\fIdate\fR:
.
.IP
Export only posts older than this date, in format YYYY\-MM\-DD\.
.
.TP
\fB\-\-post_type\fR=\fIpost_type\fR:
.
.IP
Export only posts with this post_type\.
.
.TP
\fB\-\-post__in\fR=\fIpid\fR:
.
.IP
Export all posts specified as a comma\-separated list of IDs\.
.
.TP
\fB\-\-author\fR=<login/id>:
.
.IP
Export only posts by this author\.
.
.TP
\fB\-\-category\fR=\fIcategory\-id\fR:
.
.IP
Export only posts in this category\.
.
.TP
\fB\-\-post_status\fR=\fIstatus\fR:
.
.IP
Export only posts with this status\.
.
.SH "EXAMPLES"
.
.nf

wp export \-\-dir=/tmp/ \-\-user=admin \-\-post_type=post \-\-start_date=2011\-01\-01 \-\-end_date=2011\-12\-31

wp export \-\-dir=/tmp/ \-\-post__in=123,124,125
.
.fi

