.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-HELP" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-help\fR \- Get help on a certain topic\.
.
.SH "SYNOPSIS"
wp help [\fIcommand\fR] [\-\-gen]
.
.SH "EXAMPLES"
.
.nf

# (re)generates all man pages
wp help \-\-gen

# (re)generate man pages for the `core` command
wp help \-\-gen core

# (re)generate man page only for the `core download` subcommand
wp help \-\-gen core download
.
.fi

