.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-OPTION" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-option\fR \- Manage WordPress options\.
.
.SH "SYNOPSIS"
wp option get \fIkey\fR [\-\-json]
.
.P
wp option add \fIkey\fR \fIvalue\fR [\-\-json]
.
.P
wp option update \fIkey\fR \fIvalue\fR [\-\-json]
.
.P
wp option delete \fIkey\fR
.
.SH "SUBCOMMANDS"
.
.TP
\fBadd\fR:
.
.IP
Add an option\.
.
.TP
\fBdelete\fR:
.
.IP
Delete an option\.
.
.TP
\fBget\fR:
.
.IP
Get an option\.
.
.TP
\fBupdate\fR:
.
.IP
Update an option\.
.
.SH "OPTIONS"

.
.TP
\fB\-\-json\fR:
.
.IP
Encode/decode values as JSON\.
.
.SH "EXAMPLES"
.
.nf

wp option get siteurl

wp option add my_option foobar

wp option update my_option \'{"foo": "bar"}\' \-\-json

wp option delete my_option
.
.fi

