.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-LIST" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-list\fR \- Get a list of plugins\.
.
.SH "SYNOPSIS"
wp plugin list [\-\-format=\fIformat\fR]
.
.SH "OPTIONS"
.
.TP
\fB\-\-format\fR=\fIformat\fR:
.
.IP
Output list as table, CSV or JSON\. Defaults to table\.
.
.SH "EXAMPLES"
wp plugin list \-\-format=json
