.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-STATUS" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-status\fR \- See the status of one or all plugins\.
.
.SH "SYNOPSIS"
wp plugin status [\fIplugin\fR]
.
.SH "OPTIONS"
.
.TP
\fB<plugin>\fR:
.
.IP
A particular plugin to show the status for\.

