.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-UNINSTALL" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-uninstall\fR \- Uninstall a plugin\.
.
.SH "SYNOPSIS"
wp plugin uninstall \fIplugin\fR [\-\-no\-delete]
.
.SH "OPTIONS"
.
.TP
\fIplugin\fR:
.
.IP
The plugin to uninstall\.
.
.TP
\fB\-\-no\-delete\fR:
.
.IP
If set, the plugin files will not be deleted\. Only the uninstall procedure will be run\.
.
.SH "EXAMPLES"
.
.nf

wp plugin uninstall hello
.
.fi

