.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-TOGGLE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-toggle\fR \- Toggle a plugin\'s activation state\.
.
.SH "SYNOPSIS"
wp plugin toggle \fIplugin\fR [\-\-network]
.
.SH "OPTIONS"
.
.TP
\fB<plugin>\fR:
.
.IP
The plugin to toggle\.
.
.TP
\fB\-\-network\fR:
.
.IP
If set, the plugin will be toggled for the entire multisite network\.

