.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-DELETE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-delete\fR \- Delete plugin files\.
.
.SH "SYNOPSIS"
wp plugin delete \fIplugin\fR
.
.SH "OPTIONS"
.
.TP
\fIplugin\fR:
.
.IP
The plugin to delete\.
.
.SH "EXAMPLES"
.
.nf

wp plugin delete hello
.
.fi

