.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-DEACTIVATE" "1" "May 2012" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-deactivate\fR \- Deactivate an active plugin\.
.
.SH "SYNOPSIS"
\fBwp plugin deactivate\fR \fIplugin\fR
.
.SH "OPTIONS"
.
.TP
\fB<plugin>\fR:
.
.IP
The plugin to deactivate\.

