.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-INSTALL" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-install\fR \- Install a plugin\.
.
.SH "SYNOPSIS"
wp plugin install \fIplugin|zip\fR [\-\-version=\fIversion\fR] [\-\-activate]
.
.SH "OPTIONS"
.
.TP
\fIplugin\fR:
.
.IP
A plugin slug or the path to a zip file\.
.
.TP
\fB\-\-version\fR=\fIversion\fR:
.
.IP
If set, get that particular version from wordpress\.org, instead of the stable version\.
.
.TP
\fB\-\-activate\fR:
.
.IP
If set, the plugin will be activated immediately after install\.
.
.SH "EXAMPLES"
.
.nf

wp plugin install bbpress \-\-version=2\.1 \-\-activate

wp plugin install bbpress \-\-version=dev

wp plugin install \.\./my\-plugin\.zip
.
.fi

