.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-UPDATE\-ALL" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-update\-all\fR \- Update all plugins\.
.
.SH "SYNOPSIS"
wp plugin update\-all [\-\-dry\-run]
.
.SH "OPTIONS"
.
.TP
\fB\-\-dry\-run\fR:
.
.IP
Pretend to do the updates, to see what would happen\.
.
.SH "EXAMPLES"
.
.nf

wp plugin update\-all
.
.fi

