.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-PATH" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-path\fR \- Get the path to a plugin or to the plugin directory\.
.
.SH "SYNOPSIS"
wp plugin path [\fIplugin\fR] [\-\-dir]
.
.SH "OPTIONS"
.
.TP
\fB<plugin>\fR:
.
.IP
The plugin to get the path to\. If not set, will return the path to the plugins directory\.
.
.TP
\fB\-\-dir\fR:
.
.IP
If set, get the path to the closest parent directory, instead of the plugin file\.
.
.SH "EXAMPLES"
.
.nf

cd $(wp theme path)
.
.fi

