.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-PLUGIN\-UPDATE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-plugin\-update\fR \- Update a plugin\.
.
.SH "SYNOPSIS"
wp plugin update \fIplugin\fR [\-\-version=\fIversion\fR]
.
.SH "OPTIONS"
.
.TP
\fIplugin\fR:
.
.IP
The plugin to update\.
.
.TP
\fB\-\-version=dev\fR:
.
.IP
If set, the plugin will be updated to the latest development version, regardless of what version is currently installed\.
.
.SH "EXAMPLES"
.
.nf

wp plugin update bbpress \-\-version=dev
.
.fi

