.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-POST\-LIST" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-post\-list\fR \- Get a list of posts\.
.
.SH "SYNOPSIS"
wp post list [\-\-\fIfield\fR=\fIvalue\fR] [\-\-fields=\fIfields\fR] [\-\-format=\fIformat\fR]
.
.SH "OPTIONS"
.
.TP
\fB\-\-<field>\fR=\fIvalue\fR:
.
.IP
One or more args to pass to WP_Query\.
.
.TP
\fB\-\-fields\fR=\fIfields\fR:
.
.IP
Limit the output to specific object fields\. Defaults to ID,post_title,post_name,post_date\.
.
.TP
\fB\-\-format\fR=\fIformat\fR:
.
.IP
Output list as table, CSV, JSON, or simply IDs\. Defaults to table\.
.
.SH "EXAMPLES"
.
.nf

wp post list \-\-format=ids

wp post list \-\-post_type=post \-\-posts_per_page=5 \-\-format=json

wp post list \-\-post_type=page \-\-fields=post_title,post_status
.
.fi

