.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-POST\-DELETE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-post\-delete\fR \- Delete a post by ID\.
.
.SH "SYNOPSIS"
wp post delete \fIid\fR\.\.\. [\-\-force]
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the post to delete\.
.
.TP
\fB\-\-force\fR:
.
.IP
Skip the trash bin\.
.
.SH "EXAMPLES"
.
.nf

wp post delete 123 \-\-force

wp post delete $(wp post list \-\-post_type=\'page\' \-\-format=ids)
.
.fi

