.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-POST\-EDIT" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-post\-edit\fR \- Launch system editor to edit post content\.
.
.SH "SYNOPSIS"
wp post edit \fIid\fR
.
.SH "OPTIONS"
.
.TP
\fB<id>\fR:
.
.IP
The ID of the post to edit\.
.
.SH "EXAMPLES"
.
.nf

wp post edit 123
.
.fi

