.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-POST\-DELETE" "1" "September 2012" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-post\-delete\fR \- Delete a WordPress post\.
.
.SH "SYNOPSIS"
\fBwp post delete\fR [\fIID\fR] [\-\-post_type=\fIvalue\fR] [\-\-post_author=\fIvalue\fR] [\-\-post_status=\fIvalue\fR] [\-\-force]
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the post to delete\.
.
.TP
\fB\-\-post_type\fR:
.
.IP
Trash or delete all posts of a given post type
.
.TP
\fB\-\-post_author\fR:
.
.IP
Trash or delete all posts written by a specific user
.
.TP
\fB\-\-post_status\fR:
.
.IP
Trash or delete all posts of a given post status
.
.TP
\fB\-\-force\fR:
.
.IP
Skip the trash bin\.
.
.SH "EXAMPLES"
.
.nf

wp post delete 123 \-\-force

wp post delete \-\-post_type=page \-\-post_status=draft
.
.fi

