.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-POST\-UPDATE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-post\-update\fR \- Update one or more posts\.
.
.SH "SYNOPSIS"
wp post update \fIid\fR\.\.\. \-\-\fIfield\fR=\fIvalue\fR
.
.SH "OPTIONS"
.
.TP
\fB<ID>\fR:
.
.IP
The ID of the post to update\.
.
.TP
\fB\-\-<field>\fR=\fIvalue\fR:
.
.IP
One or more fields to update\. See wp_update_post()\.
.
.SH "EXAMPLES"
.
.nf

wp post update 123 \-\-post_name=something \-\-post_status=draft
.
.fi

