.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-POST\-GENERATE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-post\-generate\fR \- Generate some posts\.
.
.SH "SYNOPSIS"
wp post generate [\-\-count=\fInumber\fR] [\-\-post_type=\fItype\fR] [\-\-post_status=\fIstatus\fR] [\-\-post_author=\fIlogin\fR] [\-\-post_date=\fIyyyy\-mm\-dd\fR] [\-\-max_depth=\fInumber\fR]
.
.SH "OPTIONS"
.
.TP
\fB\-\-count\fR=\fInumber\fR:
.
.IP
How many posts to generate\. Default: 100
.
.TP
\fB\-\-post_type\fR=\fItype\fR:
.
.IP
The type of the generated posts\. Default: \'post\'
.
.TP
\fB\-\-post_status\fR=\fIstatus\fR:
.
.IP
The status of the generated posts\. Default: \'publish\'
.
.TP
\fB\-\-post_author\fR=\fIlogin\fR:
.
.IP
The author of the generated posts\. Default: none
.
.TP
\fB\-\-post_date\fR=\fIyyyy\-mm\-dd\fR:
.
.IP
The date of the generated posts\. Default: current date
.
.TP
\fB\-\-max_depth\fR=\fInumber\fR:
.
.IP
For hierarchical post types, generate child posts down to a certain depth\. Default: 1
.
.SH "EXAMPLES"
.
.nf

wp post generate \-\-count=10 \-\-post_type=page \-\-post_date=1999\-01\-04
.
.fi

