.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-REWRITE\-STRUCTURE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-rewrite\-structure\fR \- Update the permalink structure\.
.
.SH "SYNOPSIS"
wp rewrite structure \fIpermastruct\fR [\-\-category\-base=\fIbase\fR] [\-\-tag\-base=\fIbase\fR]
.
.SH "OPTIONS"
.
.TP
\fIpermastruct\fR:
.
.IP
The new permalink structure to apply; like "/%year%/%monthnum%/%postname%"\.
.
.TP
\fB\-\-category\-base\fR=\fIcategorybase\fR:
.
.IP
Set the base for category permalinks, ie \'/category/\'\.
.
.TP
\fB\-\-tag\-base\fR=\fItagbase\fR:
.
.IP
Set the base for tag permalinks, ie \'/tag/\'\.

