.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-REWRITE\-FLUSH" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-rewrite\-flush\fR \- Flush rewrite rules\.
.
.SH "SYNOPSIS"
wp rewrite flush [\-\-soft]
.
.SH "OPTIONS"
.
.TP
\fB\-\-soft\fR:
.
.IP
Perform a soft flush \- do not overwrite \fB\.htaccess\fR\. The default is to update \fB\.htaccess\fR rules as well as rewrite rules in database\.

