.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-REWRITE\-DUMP" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-rewrite\-dump\fR \- Print current rewrite rules\.
.
.SH "SYNOPSIS"
wp rewrite dump [\-\-json]
.
.SH "OPTIONS"
.
.TP
\fB\-\-json\fR:
.
.IP
Output rules in JSON format\.

