.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-ROLES\-LIST" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-roles\-list\fR \- List one or all roles\.
.
.SH "SYNOPSIS"
wp roles list [\fIrole\-key\fR]
.
.SH "OPTIONS"
.
.TP
[\fIrole\-key\fR]:
.
.IP
Optional\. A role to return\.
.
.SH "EXAMPLES"
.
.nf

wp roles list

wp roles list editor
.
.fi

