.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-ROLE\-DELETE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-role\-delete\fR \- Delete an existing role\.
.
.SH "SYNOPSIS"
wp role delete \fIrole\-key\fR
.
.SH "OPTIONS"
.
.TP
\fIrole\-key\fR:
.
.IP
The internal name of the role, e\.g\. editor
.
.SH "EXAMPLES"
.
.nf

wp role delete approver

wp role delete productadmin
.
.fi

