.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-ROLE\-LIST" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-role\-list\fR \- List all roles\.
.
.SH "SYNOPSIS"
wp role list [\-\-fields=\fIfields\fR] [\-\-format=\fIformat\fR]
.
.SH "OPTIONS"
.
.TP
\fB\-\-fields\fR=\fIfields\fR:
.
.IP
Limit the output to specific object fields\. Defaults to name,role\.
.
.TP
\fB\-\-format\fR=\fIformat\fR:
.
.IP
Output list as table, CSV or JSON\. Defaults to table\.
.
.SH "EXAMPLES"
.
.nf

wp role list \-\-fields=role \-\-format=csv
.
.fi

