.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-SCAFFOLD\-_S" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-scaffold\-_s\fR \- Generate starter code for a theme\.
.
.SH "SYNOPSIS"
wp scaffold _s \fIslug\fR [\-\-theme_name=\fItitle\fR] [\-\-author=\fIfull\-name\fR] [\-\-author_uri=\fIhttp\-url\fR] [\-\-activate]
.
.SH "OPTIONS"
.
.TP
\fIslug\fR:
.
.IP
The slug for the new theme, used for prefixing functions\.
.
.TP
\fB\-\-activate\fR:
.
.IP
Activate the newly downloaded theme\.
.
.TP
\fB\-\-theme_name=<title>\fR:
.
.IP
What to put in the \'Theme Name:\' header in style\.css
.
.TP
\fB\-\-author=<full name>\fR:
.
.IP
What to put in the \'Author:\' header in style\.css
.
.TP
\fB\-\-author_uri=<http url>\fR:
.
.IP
What to put in the \'Author URI:\' header in style\.css

