.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-SCAFFOLD\-TAXONOMY" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-scaffold\-taxonomy\fR \- Generate PHP code for registering a custom taxonomy\.
.
.SH "SYNOPSIS"
wp scaffold taxonomy \fIslug\fR [\-\-post_types=\fIpost\-types\fR] [\-\-textdomain=\fItextdomain\fR] [\-\-theme] [\-\-plugin=\fIplugin\fR] [\-\-label=\fIlabel\fR] [\-\-raw]
.
.SH "OPTIONS"
.
.TP
\fB\-\-label=<label>\fR:
.
.IP
The text used to translate the update messages
.
.TP
\fB\-\-textdomain=<textdomain>\fR:
.
.IP
The textdomain to use for the labels\.
.
.TP
\fB\-\-theme\fR:
.
.IP
Create a file in the current theme directory, instead of sending to STDOUT\.
.
.TP
\fB\-\-plugin=<plugin>\fR:
.
.IP
Create a file in the given plugin\'s directory, instead of sending to STDOUT\.
.
.TP
\fB\-\-raw\fR:
.
.IP
Just generate the \fBregister_taxonomy()\fR call and nothing else\.

