.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-SCAFFOLD\-PLUGIN" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-scaffold\-plugin\fR \- Generate starter code for a plugin\.
.
.SH "SYNOPSIS"
wp scaffold plugin \fIslug\fR [\-\-plugin_name=\fItitle\fR] [\-\-activate]
.
.SH "OPTIONS"
.
.TP
\fB\-\-activate\fR:
.
.IP
Activate the newly generated plugin\.
.
.TP
\fB\-\-plugin_name=<title>\fR:
.
.IP
What to put in the \'Plugin Name:\' header

