.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-SEARCH\-REPLACE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-search\-replace\fR \- Search/replace strings in the database\.
.
.SH "SYNOPSIS"
wp search\-replace \fIold\fR \fInew\fR [\fItable\fR\.\.\.] [\-\-dry\-run]
.
.SH "DESCRIPTION"
This command will go through all rows in all tables and will replace all appearances of the old string with the new one\.
.
.P
It will correctly handle serialized values\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-dry\-run\fR:
.
.IP
Show report, but don\'t perform the changes\.
.
.SH "EXAMPLES"
.
.nf

wp search\-replace \'http://example\.dev\' \'http://example\.com\' \-\-dry\-run

wp search\-replace \'foo\' \'bar\' wp_posts wp_postmeta wp_terms
.
.fi

