.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-SITE\-CREATE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-site\-create\fR \- Create a site in a multisite install\.
.
.SH "SYNOPSIS"
wp site create \-\-slug=\fIslug\fR [\-\-title=\fItitle\fR] [\-\-email=\fIemail\fR] [\-\-network_id=\fInetwork\-id\fR] [\-\-private] [\-\-porcelain]
.
.SH "OPTIONS"
.
.TP
\fB\-\-slug\fR=\fIslug\fR:
.
.IP
Path for the new site\. Subdomain on subdomain installs, directory on subdirectory installs\.
.
.TP
\fB\-\-title\fR=<title>:
.
.IP
Title of the new site\. Default: prettified slug\.
.
.TP
\fB\-\-email\fR=\fIemail\fR:
.
.IP
Email for Admin user\. User will be created if none exists\. Assignement to Super Admin if not included\.
.
.TP
\fB\-\-network_id\fR=\fInetwork\-id\fR:
.
.IP
Network to associate new site with\. Defaults to current network (typically 1)\.
.
.TP
\fB\-\-private\fR:
.
.IP
If set, the new site will be non\-public (not indexed)
.
.TP
\fB\-\-porcelain\fR:
.
.IP
If set, only the site id will be output on success\.

