.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-SITE\-EMPTY" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-site\-empty\fR \- Empty a site of its content (posts, comments, and terms)\.
.
.SH "SYNOPSIS"
wp site empty [\-\-yes]
.
.SH "OPTIONS"
.
.TP
\fB\-\-yes\fR:
.
.IP
Proceed to empty the site without a confirmation prompt\.

