.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-TERM\-DELETE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-term\-delete\fR \- Delete a term\.
.
.SH "SYNOPSIS"
wp term delete \fIterm\-id\fR \fItaxonomy\fR
.
.SH "OPTIONS"
.
.TP
\fB<term\-id>\fR:
.
.IP
ID for the term to delete\.
.
.TP
\fB<taxonomy>\fR:
.
.IP
Taxonomy of the term to delete\.
.
.SH "EXAMPLES"
.
.nf

wp term delete 15 category
.
.fi

