.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-TERM\-CREATE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-term\-create\fR \- Create a term\.
.
.SH "SYNOPSIS"
wp term create \fIterm\fR \fItaxonomy\fR [\-\-slug=\fIslug\fR] [\-\-description=\fIdescription\fR] [\-\-parent=\fIterm\-id\fR] [\-\-porcelain]
.
.SH "OPTIONS"
.
.TP
\fB<term>\fR:
.
.IP
A name for the new term\.
.
.TP
\fB<taxonomy>\fR:
.
.IP
Taxonomy for the new term\.
.
.TP
\fB\-\-slug\fR=\fIslug\fR:
.
.IP
A unique slug for the new term\. Defaults to sanitized version of name\.
.
.TP
\fB\-\-description\fR=\fIdescription\fR:
.
.IP
A description for the new term\.
.
.TP
\fB\-\-parent\fR=\fIterm\-id\fR:
.
.IP
A parent for the new term\.
.
.TP
\fB\-\-porcelain\fR:
.
.IP
Output just the new term id\.
.
.SH "EXAMPLES"
.
.nf

wp term create Apple category \-\-description="A type of fruit"
.
.fi

