.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-THEME\-UPDATE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-theme\-update\fR \- Update a theme\.
.
.SH "SYNOPSIS"
\fBwp theme update\fR \fItheme\fR
.
.SH "OPTIONS"
.
.TP
\fItheme\fR:
.
.IP
The theme to update\. Can be omitted when \-\-all is passed\.
.
.TP
\fB\-\-all\fR:
.
.IP
If set, updates for all themes will be performed\. Use \fBwp theme status\fR to see which themes have updates available\.
.
.SH "EXAMPLES"
.
.nf

wp theme update twentytwelve

wp theme update \-\-all
.
.fi

