.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-THEME\-DELETE" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-theme\-delete\fR \- Delete a theme\.
.
.SH "SYNOPSIS"
wp theme delete \fItheme\fR
.
.SH "OPTIONS"
.
.TP
\fItheme\fR:
.
.IP
The theme to delete\.
.
.SH "EXAMPLES"
.
.nf

wp theme delete twentyeleven
.
.fi

