.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-THEME\-UPDATE\-ALL" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-theme\-update\-all\fR \- Update all themes\.
.
.SH "SYNOPSIS"
wp theme update\-all [\-\-dry\-run]
.
.SH "OPTIONS"
.
.TP
\fB\-\-dry\-run\fR:
.
.IP
Pretend to do the updates, to see what would happen\.
.
.SH "EXAMPLES"
.
.nf

wp theme update\-all
.
.fi

