.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-THEME\-INSTALL" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-theme\-install\fR \- Install a theme\.
.
.SH "SYNOPSIS"
wp theme install \fItheme|zip\fR [\-\-version=\fIversion\fR] [\-\-activate]
.
.SH "OPTIONS"
.
.TP
\fItheme\fR:
.
.IP
A theme slug or the path to a zip file\.
.
.TP
\fB\-\-activate\fR:
.
.IP
If set, the theme will be activated immediately after install\.
.
.SH "EXAMPLES"
.
.nf

wp theme install twentytwelve \-\-activate

wp theme install \.\./my\-theme\.zip
.
.fi

