.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-THEME\-STATUS" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-theme\-status\fR \- See the status of one or all themes\.
.
.SH "SYNOPSIS"
wp theme status [\fItheme\fR]
.
.SH "OPTIONS"
.
.TP
\fB<theme>\fR:
.
.IP
A particular theme to show the status for\.

