.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-TRANSIENT" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-transient\fR \- Manage WordPress transients\.
.
.SH "SYNOPSIS"
wp transient get \fIkey\fR [\-\-json]
.
.P
wp transient set \fIkey\fR \fIvalue\fR [\fIexpiration\fR]
.
.P
wp transient delete \fIkey\fR
.
.P
wp transient type
.
.SH "SUBCOMMANDS"
.
.TP
\fBdelete\fR:
.
.IP
Delete a transient value\.
.
.TP
\fBget\fR:
.
.IP
Get a transient value\.
.
.TP
\fBset\fR:
.
.IP
Set a transient value\. \fIexpiration\fR is the time until expiration, in seconds\.
.
.TP
\fBtype\fR:
.
.IP
See wether the transients API is using an object cache or the options table\.
.
.SH "EXAMPLES"

.
.P
wp transient set my_key my_value 300
