.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-USER\-LIST" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-user\-list\fR \- List users\.
.
.SH "SYNOPSIS"
wp user list [\-\-role=\fIrole\fR] [\-\-format=\fIformat\fR]
.
.SH "OPTIONS"
.
.TP
\fB\-\-role\fR=\fIrole\fR:
.
.IP
Only display users with a certain role\.
.
.TP
\fB\-\-format\fR=\fIformat\fR:
.
.IP
Output list as table, CSV, JSON, or simply IDs\. Defaults to table\.
.
.SH "EXAMPLES"
.
.nf

wp user list \-\-format=ids

wp user list \-\-role=administrator \-\-format=csv
.
.fi

