#!/usr/bin/env php
<?php

if(PHP_SAPI !== 'cli') {
	die('Only cli access');
}

class WP_CLI {
	static $commands = array();
	
	function add_command($name, $class) {
		self::$commands[$name] = $class;
	}
}

include 'engine/command.php';
include 'engine/config.php';
include 'library/commands/plugins.php';

// Start output buffering to stop WordPress from spitting out its usual output.

//print_r($GLOBALS['argv']);

// Remove the first entry
$arguments = array_shift($GLOBALS['argv']);

// Get the command
$command = array_shift($GLOBALS['argv']);

//
if(isset(WP_CLI::$commands[$command])) {
	new WP_CLI::$commands[$command]($GLOBALS['argv']);
}
else {
	echo 'Unknown command';
}
