<?php
	register_post_type( '{{slug}}', array(
		'description'         => __( '{{description}}', '{{textdomain}}' ),
		'public'              => {{public}},
		'exclude_from_search' => {{exclude_from_search}},
		'show_ui'             => {{show_ui}},
		'show_in_nav_menus'   => {{show_in_nav_menus}},
		'show_in_menu'        => {{show_in_menu}},
		'show_in_admin_bar'   => {{show_in_admin_bar}},
		'menu_position'       => {{menu_position}},
		'menu_icon'           => {{menu_icon}},
		'capability_type'     => '{{capability_type}}',
		'hierarchical'        => {{hierarchical}},
		'supports'            => array( {{supports}} ),
		'has_archive'         => {{has_archive}},
		'rewrite'             => {{rewrite}},
		'query_var'           => {{query_var}},
		'can_export'          => {{can_export}},
		'labels'              => array(
			'name'                => __( '{{label_plural_ucfirst}}', '{{textdomain}}' ),
			'singular_name'       => __( '{{label_ucfirst}}', '{{textdomain}}' ),
			'add_new'             => __( 'Add new {{label}}', '{{textdomain}}' ),
			'all_items'           => __( '{{label_plural_ucfirst}}', '{{textdomain}}' ),
			'add_new_item'        => __( 'Add new {{label}}', '{{textdomain}}' ),
			'edit_item'           => __( 'Edit {{label}}', '{{textdomain}}' ),
			'new_item'            => __( 'New {{label}}', '{{textdomain}}' ),
			'view_item'           => __( 'View {{label}}', '{{textdomain}}' ),
			'search_items'        => __( 'Search {{label_plural}}', '{{textdomain}}' ),
			'not_found'           => __( 'No {{label_plural}} found', '{{textdomain}}' ),
			'not_found_in_trash'  => __( 'No {{label_plural}} found in trash', '{{textdomain}}' ),
			'parent_item_colon'   => __( 'Parent {{label}}', '{{textdomain}}' ),
			'menu_name'           => __( '{{label_plural_ucfirst}}', '{{textdomain}}' ),
		),
	) );
