#!/bin/bash

# script for generating a .deb file

SOURCE_DIR=$(pwd)

rm -rf /tmp/wp-cli

mkdir -p /tmp/wp-cli/DEBIAN

cd /tmp/wp-cli

# copy php files
ROOT_DIR='usr/share/php/wp-cli'

mkdir -p $ROOT_DIR
for dir in 'php-cli-tools' 'core' 'commands'; do
	cp -r $SOURCE_DIR/$dir $ROOT_DIR/
done

rm -rf $ROOT_DIR/php-cli-tools/.git*

# copy completion file
ROOT_DIR='etc/bash_completion.d'

mkdir -p $ROOT_DIR
cp $SOURCE_DIR/bin/wp-completion.bash $ROOT_DIR/wp

# copy license file
ROOT_DIR='usr/share/doc/wp-cli'

mkdir -p $ROOT_DIR
cp $SOURCE_DIR/LICENSE $ROOT_DIR/copyright

# remove junk files
for name in '*~' '*.swp'; do
	find . -name $name -exec rm {} \;
done

# reset permsissions and ownership
chown -R root .
chgrp -R root .
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;

# use a simple bash wrapper for the command, since we know where everything is
mkdir -p usr/bin

cat > usr/bin/wp <<EOT
#!/bin/bash

php /usr/share/php/wp-cli/core/wp-cli.php "\$@"
EOT

chmod +x usr/bin/wp

cat > DEBIAN/control <<EOT
Package: wp-cli
Version: 0.2-alpha
Section: web
Priority: optional
Architecture: all
Depends: php5-cli (>= 5.3)
Installed-Size: 150
Maintainer: Cristi Burca <scribu@gmail.com>
Description: WordPress command-line interface
 A tool for controlling WordPress installations via the command-line.
EOT

dpkg --build /tmp/wp-cli
