#!/usr/bin/env bash

ln -sf $(pwd)/src/bin/wp /usr/bin/wp

for dir in /etc/bash_completion.d /usr/local/etc/bash_completion.d; do
	if [ -d $dir ]; then
		ln -sf $(pwd)/utils/wp-completion.bash $dir/wp
		break
	fi
done
