#!/bin/bash

# utility for comparing commands between two different wp-cli versions.

if [ $# -lt 3 ]; then
	echo 'usage: <version-a> <version-b> <wp-path>'
	exit 1
fi

wp_path=$3

get_syn_list() {
	git checkout $1
	wp --path=$wp_path --cmd-dump | php $(dirname $0)/syn-list.php
}

get_syn_list $1 > /tmp/wp-cli-a
get_syn_list $2 > /tmp/wp-cli-b

diff /tmp/wp-cli-a /tmp/wp-cli-b > cmd.diff

echo 'Generated cmd.diff'
