#!/bin/bash

# utility for comparing commands between two different wp-cli versions.

if [ $# -lt 3 ]; then
	echo 'usage: <version-a> <version-b> <wp-path>'
	exit 1
fi

ver_a=$1
ver_b=$2
wp_path=$3

git checkout $ver_a
wp --path=$wp_path --syn-list > /tmp/wp-cli-a

git checkout $ver_b
wp --path=$wp_path --syn-list > /tmp/wp-cli-b

diff /tmp/wp-cli-a /tmp/wp-cli-b > cmd.diff

echo 'Generated cmd.diff'
