#!/usr/bin/env bash

for dir in /usr/bin /usr/local/bin; do
	if [ -d $dir ]; then
		ln -sf $(pwd)/bin/wp $dir/wp
		break
	fi
done

for dir in /etc/bash_completion.d /usr/local/etc/bash_completion.d; do
	if [ -d $dir ]; then
		ln -sf $(pwd)/utils/wp-completion.bash $dir/wp
		break
	fi
done
