#!/usr/bin/env bash

# check that PHP is available
command -v php > /dev/null || {
	echo "can't find PHP binary" >&2
	exit 1
}

# install Composer
command -v composer > /dev/null || {
	curl -sS https://getcomposer.org/installer | php
	sudo mv composer.phar /usr/local/bin/composer
}

# install dependencies
composer install --dev

# add symlink to wp binary
for dir in /usr/bin /usr/local/bin; do
	if [ -d $dir ]; then
		sudo ln -sf $(pwd)/bin/wp $dir/wp
		break
	fi
done

# install bash completion file
for dir in /etc/bash_completion.d /usr/local/etc/bash_completion.d; do
	if [ -d $dir ]; then
		sudo ln -sf $(pwd)/utils/wp-completion.bash $dir/wp
		break
	fi
done
