#!/bin/bash

# regenerate everything:
#	./utils/doc-build

# regenerate certain files:
#	./utils/doc-build src/doc/core-update.txt

files="$@"

if [ "$files" == "" ]; then
	files=$(ls src/doc/*.txt)

	rm -rf man
	mkdir -p man
fi

for file in $files; do
	cat $file | ronn --roff --manual="WP-CLI" > man/$(basename $file .txt).1
done
