#!/bin/bash

# regenerate modified files:
#	./utils/doc-build

for file in $(git st src/doc/ --porcelain | cut -d ' ' -f 3); do
	cat $file | ronn --roff --manual="WP-CLI" > man/$(basename $file .txt).1
done
