#!/bin/bash

# regenerates modified man pages
#
# run automatically before each commit:
# ln -s ../../utils/doc-build .git/hooks/pre-commit

if [ $# -eq 0 ]; then
	files=$(git diff --cached --name-only src/docs/)
else
	files=$@
fi

if ! which ronn > /dev/null; then
	echo "doc-build: ronn is not installed"
	exit 1
fi

for file in $files; do
	man_file=man/$(basename $file .txt).1
	cat $file | ronn --roff --manual="WP-CLI" > $man_file
	git add $man_file
done
