#!/usr/bin/env sh

# Special case for *AMP installers, since they normally don't set themselves
# as the default cli php out of the box.
for amp_php in $(cat $(dirname $0)/amp-paths.txt); do
	if [ -x $amp_php ]; then
		echo $amp_php
		exit
	fi
done

which php || which php-cli

if [ $? -eq 0 ]; then
	exit
fi

echo "no PHP binary found" >&2
exit 1
