#!/bin/bash

if [ "$BASH_SOURCE" = "$0" ]; then
	echo "This file should not be executed. It should be sourced into your current shell like this:"
	echo
	echo "source $BASH_SOURCE"
	echo
	echo "Add the above line to your .bashrc or .bash_profile to have this environment set up"
	echo "automatically when you log in."
	exit 1
fi

[ -f composer.phar ] || curl -sS https://getcomposer.org/installer | php

php composer.phar install

DIR=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)

alias wp='$DIR/../bin/wp'

. $DIR/wp-completion.bash
