#!/bin/bash

set -ex

# create bunch of directories that phing complains about
mkdir -p src/data
mkdir -p src/tests/unit-tests/php 
mkdir -p src/www 
mkdir -p src/docs

# generate package
find -name '*~' -delete
phing pear-package

version=$(cat dist/lastBuilt)
version="${version/*wpcli-/}"
version="${version/.tgz/}"

#sudo phing install-system

# update channel files
cd ../wp-cli-pear
pirum add . ../wp-cli/dist/wpcli-$version.tgz
pirum build .

# push changes
git add -A
git ci -m "release $version"
git push origin gh-pages
